# Workflow name - appears in GitHub Actions UI
name: Publish to Thunderstore

# Trigger this workflow when a release is published
# This means creating a new release in the GitHub UI will start the publishing process
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get the correct version number from tags
          fetch-depth: 0
      
      # Set up Python environment for the Thunderstore CLI
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # Install the Thunderstore CLI tool
      - name: Install tcli
        run: pip install tcli
        
      # Publish the modpack to Thunderstore
      # IMPORTANT: Customize the package-name parameter below to match your modpack name
      - name: Publish to Thunderstore
        env:
          # This uses the THUNDERSTORE_TOKEN secret you must set in your repository settings
          THUNDERSTORE_API_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF_NAME#v}
          
          # Display information about the publishing process
          echo "Publishing modpack to Thunderstore"
          echo "Version: $VERSION"
          echo "Owner: ${{ github.repository_owner }}"
          
          # Publish using tcli
          # CUSTOMIZE: Change 'valheim-modpack-template' below to your actual modpack name
          tcli publish \
            --token $THUNDERSTORE_API_TOKEN \
            --package-name valheim-modpack-template \
            --package-version $VERSION \
            --namespace ${{ github.repository_owner }} \
            --community valheim \
            --categories Modpacks \
            --file .
